services:

  literature-be:
    image: team2/literature/backend:production
    restart: always
    environment:
      DB_USERNAME: team2
      DB_PASSWORD: Thebe@tles45
      DB_DATABASE: literature
      DB_HOST: 103.196.153.76
    ports:
      - "5000:5000"

  literature-be-backup:
    image: team2/literature/backend:production
    restart: always
    environment:
      DB_USERNAME: team2
      DB_PASSWORD: Thebe@tles45
      DB_DATABASE: literature
      DB_HOST: 103.196.153.76
    ports:
      - "5001:5000"
